#!/usr/bin/env python3

SCRIPT_ERR_OK = 0,
SCRIPT_ERR_UNKNOWN_ERROR = 1
SCRIPT_ERR_EVAL_FALSE = 2
SCRIPT_ERR_OP_RETURN = 3

# Max sizes
SCRIPT_ERR_SCRIPT_SIZE = 4
SCRIPT_ERR_PUSH_SIZE = 5
SCRIPT_ERR_OP_COUNT = 6
SCRIPT_ERR_STACK_SIZE = 7
SCRIPT_ERR_SIG_COUNT = 8
SCRIPT_ERR_PUBKEY_COUNT = 9

# Failed verify operations
SCRIPT_ERR_VERIFY = 10
SCRIPT_ERR_EQUALVERIFY = 11
SCRIPT_ERR_CHECKMULTISIGVERIFY = 12
SCRIPT_ERR_CHECKSIGVERIFY = 13
SCRIPT_ERR_NUMEQUALVERIFY = 14

# Logical/Format/Canonical errors
SCRIPT_ERR_BAD_OPCODE = 15
SCRIPT_ERR_DISABLED_OPCODE = 16
SCRIPT_ERR_INVALID_STACK_OPERATION = 17
SCRIPT_ERR_INVALID_ALTSTACK_OPERATION = 18
SCRIPT_ERR_UNBALANCED_CONDITIONAL = 19

# CHECKLOCKTIMEVERIFY and CHECKSEQUENCEVERIFY
SCRIPT_ERR_NEGATIVE_LOCKTIME = 20
SCRIPT_ERR_UNSATISFIED_LOCKTIME = 21

# Malleability
SCRIPT_ERR_SIG_HASHTYPE = 22
SCRIPT_ERR_SIG_DER = 23
SCRIPT_ERR_MINIMALDATA = 24
SCRIPT_ERR_SIG_PUSHONLY = 25
SCRIPT_ERR_SIG_HIGH_S = 26
SCRIPT_ERR_SIG_NULLDUMMY = 27
SCRIPT_ERR_PUBKEYTYPE = 28
SCRIPT_ERR_CLEANSTACK = 29
SCRIPT_ERR_MINIMALIF = 30
SCRIPT_ERR_SIG_NULLFAIL = 31

# softfork safeness
SCRIPT_ERR_DISCOURAGE_UPGRADABLE_NOPS = 32
SCRIPT_ERR_DISCOURAGE_UPGRADABLE_WITNESS_PROGRAM = 33

# segregated witness
SCRIPT_ERR_WITNESS_PROGRAM_WRONG_LENGTH = 34
SCRIPT_ERR_WITNESS_PROGRAM_WITNESS_EMPTY = 35
SCRIPT_ERR_WITNESS_PROGRAM_MISMATCH = 36
SCRIPT_ERR_WITNESS_MALLEATED = 37
SCRIPT_ERR_WITNESS_MALLEATED_P2SH = 38
SCRIPT_ERR_WITNESS_UNEXPECTED = 39
SCRIPT_ERR_WITNESS_PUBKEYTYPE = 40

# Constant scriptCode
SCRIPT_ERR_OP_CODESEPARATOR = 41
SCRIPT_ERR_SIG_FINDANDDELETE = 42

SCRIPT_ERR_ERROR_COUNT = 43
